"""empty message

Revision ID: ea063f8f931a
Revises: a3ed8022f4f8
Create Date: 2022-01-04 23:13:33.414676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea063f8f931a'
down_revision = 'a3ed8022f4f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('Artist', sa.Column('genres', sa.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('Artist', 'genres')
    # ### end Alembic commands ###
    pass