"""empty message

Revision ID: ed3b54b5aecd
Revises: 
Create Date: 2022-03-14 15:17:23.743420

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ed3b54b5aecd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testnodegroups')
    op.drop_table('testnodestest')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testnodestest',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fabric', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hostname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('role', postgresql.ENUM('access_leaf', 'border_leaf', 'spine', name='noderole'), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('standalone', 'vpc', name='nodetype'), autoincrement=False, nullable=True),
    sa.Column('vpc_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['vpc_id'], ['nodegroups.id'], name='testnodestest_vpc_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='testnodestest_pkey')
    )
    op.create_table('testnodegroups',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fabric', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('node_1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('node_2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='testnodegroups_pkey')
    )
    # ### end Alembic commands ###
